compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"

packageExtensions:
  croact-css-styled@1.1.9:
    dependencies:
      croact: 1.0.4
  doctrine@3.0.0:
    dependencies:
      assert: 2.0.0
  rc-time-picker@3.7.3:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1
  rc-trigger@2.6.5:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-4.4.0.cjs
